[run]
allow-parallel-runners = true

[linters]
# Use everything but the style-related linters by default
presets = [
  "bugs",
  "comment",
  "complexity",
  "error",
  "format",
  "import",
  "metalinter",
  "module",
  "performance",
  "sql",
  "style",
  "test",
  "unused",
]

disable = [
  "depguard",        # allow list maintained elsewhere
  "exhaustruct",     # structs must be allowed to use default values for terseness
  "forcetypeassert", # covered by errcheck
  "gci",             # not ready for production use [2021-MAY-18]
  "godot",           # ending periods stutter when EOL is struct field label
  "gomoddirectives", # using go modules so disabling as recommended
  "gomodguard",      # allow list maintained elsewhere
  "nlreturn",        # leave whitespace shaping to personal editor config
  "nonamedreturns",  # gram code uses named returns currently
  "paralleltest",    # test runner runs tests in parallel by default
  "varnamelen",      # forces long names in short scopes
  "wsl",             # leave whitespace shaping to personal editor config
]

[linters-settings.errcheck]
check-type-assertions = true                                      # should try to avoid panic scenario
check-blank = true                                                # don't ignore errors
exclude-functions = ["fmt.Fprint", "fmt.Fprintf", "fmt.Fprintln"]

[linters-settings.goconst]
ignore-tests = true

[linters-settings.gofumpt]
extra-rules = true # aggressive fumpt

[linters-settings.goimports]
local-prefixes = "github.com/janrain"

[linters-settings.gosec]
excludes = ["G307"]

[linters-settings.funlen]
lines = -1 # only count statements, blank lines and comments shouldn't penalize a func

[linters-settings.revive]
rules = [
  { name = "import-shadowing" },
  # Defaults
  { name = "var-declaration" },
  { name = "package-comments" },
  { name = "dot-imports" },
  { name = "blank-imports" },
  { name = "exported" },
  { name = "var-naming" },
  { name = "indent-error-flow" },
  { name = "range" },
  { name = "errorf" },
  { name = "error-naming" },
  { name = "error-strings" },
  { name = "receiver-naming" },
  { name = "increment-decrement" },
  { name = "error-return" },
  { name = "unexported-return" },
  { name = "time-naming" },
  { name = "context-keys-type" },
  { name = "context-as-argument" },
  { name = "empty-block" },
  { name = "superfluous-else" },
  { name = "unused-parameter" },
  { name = "unreachable-code" },
  { name = "redefines-builtin-id" },
]

[issues]
exclude-use-default = false # skip golang-ci linter omissions
exclude-dirs = ["vendor"] # ignore vendor folder
include = [
  "EXC0001",
  "EXC0002",
  "EXC0003",
  "EXC0004",
  "EXC0005",
  "EXC0006",
  "EXC0007",
  "EXC0008",
  "EXC0009",
  "EXC0010",
  "EXC0011",
]
